resolver: lts-7.14
packages:
- '.'
- location:
    git: git@github.com:haroldcarr/test-hunit-util.git
    commit: 76246854236d38ae569c0c7907abbd506902cd05
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
